import { TModel } from "./TModel.js";
import { Viewport } from "./Viewport.js";

/**
 * Represents a node in a tree generated by the BracketGenerator from a large list,
 * used to restrict calculations to only the visible branches.
 */
class Bracket extends TModel {
    constructor(parent) {
        super("BI");
        this.parent = parent;
    }
    
    canHaveDom() {
        return false;
    }
    
    getItemOverflowMode() {
        return 'never';
    }

    shouldBeBracketed() {
        return false;
    }
    
    excludeDefaultStyling() {
        return true;
    }
    
    isIncluded() {
        return false;
    }

    getWidth() {
        return this.getContentWidth();
    }

    getHeight() {
        return this.getContentHeight();
    }

    getBaseWidth() {
        return this.bottomBaseWidth;
    }

    getContainerOverflowMode() {
        return this.getRealParent().getContainerOverflowMode();
    }
    
    getTopBaseHeight() {
        return this.topBaseHeight;
    }
    
    isVisible() {
        return this.visibilityStatus.top && this.visibilityStatus.bottom;
    }
    
    getBracketThreshold() {
        return this.getRealParent().getBracketSize();
    }
    
    addToParentVisibleChildren() {}

    createViewport() {
        this.viewport = this.viewport || new Viewport();

        this.viewport.xNext = this.x;
        this.viewport.xNorth = this.x;
        this.viewport.xEast = this.x;
        this.viewport.xSouth = this.x;
        this.viewport.xWest = this.x;
        
        this.viewport.absX = this.getRealParent().viewport.absX;
        this.viewport.absY = this.getRealParent().viewport.absY;

        this.viewport.scrollTop = this.getRealParent().viewport.scrollTop;
        this.viewport.scrollLeft = this.getRealParent().viewport.scrollLeft;
        this.viewport.xOverflowReset = this.getRealParent().viewport.xOverflowReset;        
        this.viewport.xOverflowLimit = this.getRealParent().viewport.xOverflowLimit;

        this.viewport.yNext = this.y;
        this.viewport.yNorth = this.y;
        this.viewport.yWest = this.y;
        this.viewport.yEast = this.y;
        this.viewport.ySouth = this.getRealParent().viewport.ySouth;
                
        return this.viewport;   
    }
   
    getRealParent() {
        return this.realParent;
    }
    
    calcAbsolutePosition(x, y) {
        this.absX = x + this.getRealParent().absX;
        this.absY = y + this.getRealParent().absY;
    }

    shouldCalculateChildren() {
        const result = this.isVisible() || this.currentStatus === 'new';
        this.currentStatus = undefined;
        return result;
    }
    
    validateVisibilityInParent() {
        return this.getChildren().length > 0 ? this.getChild(0).validateVisibilityInParent() : false;
    }
    
    getChildren() {
        return this.allChildrenList;
    }
}

export { Bracket };
